# -*- coding: utf-8 -*-
"""Customer-Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qkSvJ2nIND2dGRKJKgTXYRRMT9kqyA1C

CUSTOMER CHURN PROJECT :
In the telecom industry, customers churning to competitors is big issue. This project analyzes the company data and finds insights about why customers might be churning out, and establish steps to prevent it.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick

from google.colab import drive
drive.mount('/content/drive')

customer_churn = pd.read_csv("/content/drive/MyDrive/Churn project/customer_churn.csv")

#customer_churn = pd.read_csv('customer_churn.csv')

"""Data Manipulation"""

customer_churn.head()

customer_churn.tail()

# DATA MANIPULATION
# Extracting 5th column from the entire dataset

customer_5 = customer_churn.iloc[:,4]
customer_5.head()

# Extracting the 15th column

customer_15 = customer_churn.iloc[:,14]
customer_15.head()

# Extracting all the male senior citizens who pay via Electronic check

senior_male_electronic = customer_churn[(customer_churn['gender'] == 'Male') & (customer_churn['SeniorCitizen'] == 1) & (customer_churn['PaymentMethod'] == 'Electronic check')]
senior_male_electronic.head()

# Exctracting all the customers whose tenure is greater than 70 months or their monthly charges are over $100

customer_total_tenure = customer_churn[(customer_churn['tenure'] > 70) | (customer_churn['MonthlyCharges'] > 100)]
customer_total_tenure.head()

# Extracting customers whose contract is of two years, payment method is mailed check, and the value of Churn is yes

two_mail_yes = customer_churn[(customer_churn['Contract'] == "Two year") & (customer_churn['PaymentMethod'] == "Mailed check") & (customer_churn['Churn'] == 'Yes')]
two_mail_yes.head()

# Extracting 333 customers at random

customer_333 = customer_churn.sample(n = 333, random_state = 42)
customer_333.head()

# Getting the count of different levels from Churn column

customer_churn['Churn'].value_counts()

"""Data Visualization"""

# Bar-plot to visualize the distribution of internet services

plt.bar(customer_churn['InternetService'].value_counts().keys().tolist(), customer_churn['InternetService'].value_counts().tolist(), color = 'orange')
plt.xlabel('Categories of Internet Service')
plt.ylabel('Count of Categories')
plt.title('Distribution of Internet Service')
plt.show()

"""Inference (Distribution of Service): Out of the cutomers who do have internet service, majority have opted for Fiber Optic."""

# Histogram to visualize the tenure distribution

plt.hist(customer_churn['tenure'], bins=30, color = 'green')
plt.xlabel('Months')
plt.ylabel('No. of Customers')
plt.title('Distribution of tenure')
plt.show()

"""Inference (Distribution of tenure): Customers tend to leave the service between 10 to 65 months"""

# Scatter plot to visualize how monthly charges change with tenure

plt.scatter(customer_churn['tenure'], customer_churn['MonthlyCharges'])
plt.xlabel('Tenure of customer')
plt.ylabel('Monthly charges of customer')
plt.title('Tenure vs Monthly Charges')
plt.show()

"""Inference (Tenure vs monthly charges): There are less customers whose monthly bills are around $35, most around $20 and $100."""

# Box plot to visualize the effect of contract on tenure

sns.boxplot(x = customer_churn['Contract'], y = customer_churn['tenure'])
plt.xlabel('Contract')
plt.ylabel('Tenure')
plt.title('Contract vs Tenure')
plt.show()

"""Inference (Contract vs tenure): Customers with two year contracts tend to last longer with the service

LINEAR REGRESSION (Tenure(independent), Monthly Charges(dependent))
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Defining the dependent and independent variable
X = np.array(customer_churn['tenure'])
X_r = X.reshape(-1,1) # Reshaping the array
y = customer_churn['MonthlyCharges']

# Splitting the data into training and testing set in the ratio 70:30
X_rtrain, X_rtest, y_train, y_test = train_test_split(X_r, y, test_size = 0.3, random_state = 42)

# Building and training the linear regression model on the training set
linear_train = LinearRegression()
linear_train.fit(X_rtrain, y_train)

# Making prediction on the test set
y_pred = linear_train.predict(X_rtest)

# Finding the root mean squared error
error = np.sqrt(mean_squared_error(y_test,y_pred))

print("The root mean squared error is: ",error)

"""LOGISTIC REGRESSION (Monthly Charges(independent), Churn(dependent))"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

# Defining the dependent and independent variable
X = np.array(customer_churn['MonthlyCharges'])
X_r = X.reshape(-1,1) # Reshaping the array
y = customer_churn['Churn']

# Dividing into train and test data with the ratio 65:35
X_rtrain, X_rtest, y_train, y_test = train_test_split(X_r, y, test_size = 0.35, random_state=42)

log_train = LogisticRegression()
log_train.fit(X_rtrain, y_train)

# Predicting on test data
y_pred = log_train.predict(X_rtest)

# Building the confusion matrix and getting the accuracy score
conf_matrix = confusion_matrix(y_test,y_pred)
acc_score = accuracy_score(y_test, y_pred)

print("Confusion matrix = \n", conf_matrix)
print("Accuracy Score = ", acc_score)

"""LOGISTIC REGRESSION ( Independent - Tenure, Monthly Charges) & (Dependent - Churn)"""

# Defining independent and depedent variables
X = customer_churn[['tenure','MonthlyCharges']]
y = customer_churn['Churn']

# Dividing into train and test data with the ratio 80:20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Making a multiple logistic regression model
multi_log = LogisticRegression()
multi_log.fit(X_train, y_train)

# Predicting on test data
y_pred = multi_log.predict(X_test)

multi_cm = confusion_matrix(y_test, y_pred)
multi_acc  = accuracy_score(y_test,y_pred)

print("Confusion Matrix (Multiple Logistic Regression): \n", multi_cm)
print("Accuracy Score (Multiple Logistic Regression): ",multi_acc)

"""DECISION TREE CLASSIFIER (Independent - Tenure) & (Dependent - Churn)"""

from sklearn.tree import DecisionTreeClassifier

# Defining independent and depedent variables
X = np.array(customer_churn['tenure'])
X_r = X.reshape(-1,1) # Reshaping the array
y = customer_churn['Churn']

# Splitting into train and test data with the ratio 80:20
X_rtrain, X_rtest, y_train, y_test = train_test_split(X_r, y, test_size = 0.2, random_state = 42)

# Building the Decision Tree Classifier model
dt_model = DecisionTreeClassifier()
dt_model.fit(X_rtrain, y_train)

# Predicting test data
y_pred = dt_model.predict(X_rtest)

# Calculating confusion matrix and model accuracy score
dt_cm = confusion_matrix(y_test, y_pred)
dt_acc = accuracy_score(y_test, y_pred)
print("Confusion matrix (Decision Tree Classifier): \n", dt_cm)
print("Accuracy Score (Decision Tree Classifier): ", dt_acc)

"""Random Forest Classifier (Independent - Tenure, Monthly Charges) & (Dependent - Churn)"""

from sklearn.ensemble import RandomForestClassifier

# Defining independent and dependent variables
X = customer_churn[['tenure','MonthlyCharges']]
y = customer_churn['Churn']

# Splitting into train and test data with the ratio 70:30
X_train , X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

# Building the Random Forest Classifier Model
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

# Predicting test data
y_pred = rf_model.predict(X_test)

rf_cm = confusion_matrix(y_test, y_pred)
rf_acc = accuracy_score(y_test, y_pred)
print("Confusion matrix (Random Forest Classifier): \n",rf_cm)
print("Accuracy Score (Random Forest Classifier): ",rf_acc)

"""Multiple Logistic Regression model provided the best accuracy for this problem. Steps can be taken to better the marketing for the two year plan (For ex: better offers on contract phones for two years) to avoid customer churn out."""